### ISSUE TITLE
Checklist of 0.0.1 version release

### ISSUE THREAD

**Issue by changhiskhan** [eto-ai/rikai#36]
Pre-release:
- [x] Remove /conf directory? (keep for docker image)
~- [ ] Include jar with pypi package? (if not, must change spark tests)~
- [x] #19 
~- [ ] #23~
- [x] add an image-based example notebook
- [x] Any more docs needed?

Release:
- [ ] test docker image
- [ ] upload to dockerhub? (cpu-only)
- [ ] test doc build, incl. `sbt doc`
~-[ ] Do we want bumpversion? ~
- [x] Are we settled on semantic versioning?
- [x] #26 
- [ ] make pypi release

**Comment by eddyxu** [comment]
I added Milestones to track the tickets

https://github.com/eto-ai/rikai/milestone/1

**Comment by changhiskhan** [comment]
subsumed by milestone
